Add .oppositeYAxis DisplayValue to show POI Labels at the opposite end
willdale/SwiftUICharts pull request #161
Opened 2022-01-11 02:45 UTC by kunalverma25

Addition of .oppositeYAxis DisplayValue Enum for showing POI labels at the opposite end of yAxis
Enhancement for #160

2022-01-11 02:51 UTC, kunalverma25 commented
Hey @willdale 
This PR adds an additional option for the POI label position for the opposite end of the axis, w/o modifying current implementation.

2022-01-13 13:46 UTC, willdale commented
@kunalverma25 I'm happy in principal with the changes for v2, they will likely not get ported forward into v3 as the implementation has completely changed for the POI.

I ran out of time to do a full review before work tis morning but one thing that jumped out was the use of `AnyView`. It is generally not recommended to use `AnyView` - See [Natascha Fadeeva's article](https://tanaschita.com/20210802-how-to-avoid-using-anyview-in-swiftui/) or [swiftbysundell's](https://www.swiftbysundell.com/articles/avoiding-anyview-in-swiftui/).

2022-01-15 14:46 UTC, kunalverma25 commented
I’ll be more than happy to add these changes to the new implementation of the POIs when finalized.
As for AnyView I get that it prevents optimizations and updates but the use case here itself doesn’t require those as the view itself(icon) is just statically passed and the redrawing depends on graph data.
Besides adding the same functionality via ViewBuilders will only create unnecessary bridging code from ViewModifiers to Protocol Conformances and force to manually typecast the passed in views which basically defeats the whole purpose of not using AnyView.

2022-01-16 09:36 UTC, willdale requested changes
- [ ] Rename `oppositeYAxis` and update the it to take positioning
- [ ] I think for now, remove: `labelIcon: AnyView`

2022-01-16 09:36 UTC, willdale commented on Sources/SwiftUICharts/SharedLineAndBar/Extras/LineAndBarEnums.swift
> +    case oppositeYAxis(specifier: String, formatter: NumberFormatter? = nil)
Could it be `.position(at location: CGFloat, ...)` this place it as a percentile of total width within the chart?

2022-01-16 09:59 UTC, willdale commented
Look back at the issue [#160](https://github.com/willdale/SwiftUICharts/issues/160) you raised, is the `labelIcon` for adding the '$'  symbol? If so then you could use the number formatter.

2022-01-16 15:16 UTC, kunalverma25 commented
I also wanted to add some image, sf-symbol and/or anything non-text.

2022-01-17 05:45 UTC, kunalverma25 commented
@willdale Updated the PR..

2022-01-18 06:45 UTC, willdale approved these changes

2022-01-30 11:29 UTC, merged